name: taximate
description: A TaxiMate app for ride-sharing.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  smooth_page_indicator: '^1.2.0+3'
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/taxi1.jpg
    - assets/images/taxi2.jpg
    - assets/images/taxi3.jpg
    - assets/images/taxi4.jpg